language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories: 
    - node_modules
notifications.email: false
node_js: node
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - yarn test:prod
  - yarn build
after_script: greenkeeper-lockfile-upload
after_success:
  - yarn deploy-docs
  - yarn semantic-release
